# Generated by Django 3.0.6 on 2022-05-10 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transport',
            name='empresa',
        ),
    ]
