# Generated by Django 3.0.6 on 2022-05-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_auto_20220513_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flete',
            old_name='empresa',
            new_name='company',
        ),
    ]
