# Generated by Django 3.0.6 on 2022-05-14 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0005_auto_20220513_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flete',
            old_name='date',
            new_name='entry_date',
        ),
    ]
