# Generated by Django 3.0.6 on 2022-05-14 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0006_auto_20220513_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flete',
            options={'verbose_name': 'Flete', 'verbose_name_plural': 'Fletes'},
        ),
        migrations.AddField(
            model_name='flete',
            name='vehiculo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Transport'),
            preserve_default=False,
        ),
    ]
