# Generated by Django 3.0.6 on 2022-05-14 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0007_auto_20220513_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flete',
            options={'verbose_name': 'flete', 'verbose_name_plural': 'fletes'},
        ),
    ]
