# Generated by Django 3.0.6 on 2022-05-14 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0008_auto_20220513_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flete',
            name='vehiculo',
        ),
    ]
