# Generated by Django 3.0.6 on 2022-05-24 01:13

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0010_flete_vehiculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flete',
            options={'verbose_name': 'Flete', 'verbose_name_plural': 'Fletes'},
        ),
        migrations.AlterModelManagers(
            name='flete',
            managers=[
                ('objects2', django.db.models.manager.Manager()),
            ],
        ),
    ]
