# Generated by Django 3.0.6 on 2022-05-29 21:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0011_auto_20220523_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heavy_machinery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('description', models.CharField(max_length=60, verbose_name='descripcion')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Maquinaria',
                'verbose_name_plural': 'Maquinarias',
            },
        ),
        migrations.CreateModel(
            name='sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='precio de la renta')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Heavy_machinery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(blank=True, null=True, verbose_name='fehca de transaccion ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='precio de la renta')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Heavy_machinery')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
